### ISSUE TITLE
Does GEDI support the Illumina microarray data?

### ISSUE THREAD

**Issue by wanhui5867** [MNStokholm/GEDI#6]
HI,

Thanks for developing the nice tool! I have two questions:

1. Does GEDI support integrating RNAseq with Illumina microarray data? If yes, which input datasets of Illumina microarray are needed?
2. Could GEDI also accept TPM/FPKM data of RNA-seq as input data type?

Best,
Hui

**Comment by MNStokholm** [comment]
I'm glad you like it and that my bachelor's thesis is being used. In theory, GEDI can integrate any type of RNAseq and microarray data. However, the ReadGE function only supports RNAseq counts, Affymetrix microarray, and Agilent microarray.

You can, however, read the data yourself and store the datasets in a list since this is basically what ReadGE does. Then you should be able to pass the list of datasets to the GEDI function as usual. It is also a matter of whether the microarray probe IDs are available in the biomaRt database. The GEDI function uses biomaRt to map microarray probe IDs to ensemble gene IDs.

To answer your second question, GEDI will accept TPM/FPKM data, but I wouldn't recommend integrating TPM/FPKM data with microarray data. However, there should be no issue in merging multiple TPM/FPKM datasets with each other. 

Did that answer your questions?

**Comment by wanhui5867** [comment]
Thanks for your kind reply Mathias! It answered my questions.
